// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChVMKv2S7GmtZPyFjPg5wzmS6jVhAUx0Q',
    appId: '1:124187377848:web:c433481ee322247722744d',
    messagingSenderId: '124187377848',
    projectId: 'pakwheels-338b1',
    authDomain: 'pakwheels-338b1.firebaseapp.com',
    storageBucket: 'pakwheels-338b1.firebasestorage.app',
    measurementId: 'G-3SN24P5ZZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5G-RdETyN0JwTgKU5vIHKgpjtC5ACd6g',
    appId: '1:124187377848:android:7383da59136b68e822744d',
    messagingSenderId: '124187377848',
    projectId: 'pakwheels-338b1',
    storageBucket: 'pakwheels-338b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBirufuMRTB4trllE1LM7xD--7fYOzJPjc',
    appId: '1:124187377848:ios:b2a6df05a58fdee422744d',
    messagingSenderId: '124187377848',
    projectId: 'pakwheels-338b1',
    storageBucket: 'pakwheels-338b1.firebasestorage.app',
    iosBundleId: 'com.example.pakwheels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBirufuMRTB4trllE1LM7xD--7fYOzJPjc',
    appId: '1:124187377848:ios:b2a6df05a58fdee422744d',
    messagingSenderId: '124187377848',
    projectId: 'pakwheels-338b1',
    storageBucket: 'pakwheels-338b1.firebasestorage.app',
    iosBundleId: 'com.example.pakwheels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChVMKv2S7GmtZPyFjPg5wzmS6jVhAUx0Q',
    appId: '1:124187377848:web:91ba6826261221c522744d',
    messagingSenderId: '124187377848',
    projectId: 'pakwheels-338b1',
    authDomain: 'pakwheels-338b1.firebaseapp.com',
    storageBucket: 'pakwheels-338b1.firebasestorage.app',
    measurementId: 'G-6KG04B45LB',
  );
}
